# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(max_length=512)),
                ('nucleotide_change', models.TextField()),
                ('protein_change', models.TextField()),
                ('other_mappings', models.TextField()),
                ('alias', models.CharField(max_length=512)),
                ('transcripts', models.CharField(max_length=512)),
                ('region', models.CharField(max_length=512)),
                ('reported_classification', models.TextField()),
                ('inferred_classification', models.TextField()),
                ('source', models.CharField(max_length=512)),
                ('last_evaluated', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(max_length=512)),
                ('submitter_comment', models.TextField()),
                ('assembly', models.CharField(max_length=512)),
                ('chr', models.CharField(max_length=512)),
                ('genomic_start', models.CharField(max_length=512)),
                ('genomic_stop', models.CharField(max_length=512)),
                ('ref', models.CharField(max_length=512)),
                ('alt', models.CharField(max_length=512)),
                ('accession', models.CharField(max_length=512)),
                ('reported_ref', models.CharField(max_length=512)),
                ('reported_alt', models.CharField(max_length=512)),
            ],
            options={
                'ordering': ('gene',),
            },
        ),
    ]
